workflows:
  build:
    jobs:
      - build:
          context: Salsify
      - lint
      - test:
          matrix:
            parameters:
              ruby_version:
                - "2.7.2"
                - "3.0.0"
version: 2.1
jobs:
  build:
    docker:
      - image: salsify/ruby_ci:2.7.2
      - image: circleci/postgres:12.3-ram
        environment:
          POSTGRES_USER: "ubuntu"
          POSTGRES_DB: "circle_test"
          POSTGRES_HOST_AUTH_METHOD: "trust"
    environment:
      CIRCLE_TEST_REPORTS: "test-results"
      PGHOST: "localhost"
      PGUSER: "ubuntu"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gems-ruby-2.7.2-{{ checksum "delayed_job_chainable_hooks.gemspec" }}-{{ checksum "Gemfile" }}
            - v1-gems-ruby-2.7.2-
      - run:
          name: Install Gems
          command: |
            if ! bundle check --path=vendor/bundle; then
              bundle install --path=vendor/bundle --jobs=4 --retry=3
              bundle clean
            fi
      - save_cache:
          key: v1-gems-ruby-2.7.2-{{ checksum "delayed_job_chainable_hooks.gemspec" }}-{{ checksum "Gemfile" }}
          paths:
            - "vendor/bundle"
            - "gemfiles/vendor/bundle"
      - run:
          name: Wait for Database
          command: dockerize -wait tcp://localhost:5432 -timeout 60s
      - run:
          name: Wait for Database User
          command: t=30; for i in `seq $t`; do psql -h localhost -p 5432 -U ubuntu -d circle_test -c '\q' && break; [ $i -eq $t ] && return 2; sleep 1; done;
  lint:
    docker:
      - image: salsify/ruby_ci:2.7.2
    working_directory: ~/delayed_job_chainable_hooks
      - run:
          name: Run Rubocop
          command: bundle exec rubocop --config .rubocop.yml
  test:
    parameters:
      ruby_version:
        type: string
    docker:
      - image: salsify/ruby_ci:<< parameters.ruby_version >>
      - image: circleci/postgres:12.3-ram
        environment:
          POSTGRES_USER: "ubuntu"
          POSTGRES_DB: "circle_test"
          POSTGRES_HOST_AUTH_METHOD: "trust"
    environment:
      CIRCLE_TEST_REPORTS: "test-results"
      PGHOST: "localhost"
      PGUSER: "ubuntu"
    working_directory: ~/delayed_job_chainable_hooks
    steps:
      - run:
          name: Run Tests
          command: |
            bundle exec rspec --format RspecJunitFormatter --out $CIRCLE_TEST_REPORTS/rspec/junit.xml --format progress spec
      - store_test_results:
          path: "test-results"
