workflows:
  build:
    jobs:
    - lint:
        ruby_version: 2.7.7
    - test:
        matrix:
          parameters:
            ruby_version:
            - 2.7.7
            - 3.0.5
            - 3.1.3
            - 3.2.0
            - 3.3.0
